### ISSUE TITLE
Pre-release task list

### ISSUE THREAD

**Issue by tanelj** [Voog/design-firenze#5]
Bug list:
- [x] Empty footer area should be wider (currently ~30px)
- [x] In edit mode there has to few space between gallery area and text area when gallery is next to text area (it's ok in preview mode)
- [x] Do not show parent page on 2nd level menu
- [x] Search is missing on sub page layouts
- [x] Footer is misplaced (is aligned to left not centre) in mobile views
- [x] `data.fb_image` should be checked to against `nil` and `""` [values](https://github.com/Edicy/design-firenze/blob/master/layouts/front_page.tpl#L9)
